### ISSUE TITLE
Security vulnerability through npm-check-updates

### ISSUE THREAD

**Issue by grover** [cmaurer/relative.time.parser#7]
Hi,

thanks for this great plugin. I'm using it for a HomeKit/homebridge plugin (my homebridge-calendar) and one of its users has reported a security vulnerability for it: It turns out that the source is a broken version of the debug module, which is imported through npm-check-updates. Please upgrade the dependencies of relative-time-parser and publish a new version.

See https://nodesecurity.io/advisories/534 for more details.

Thanks!
grover

**Comment by cmaurer** [comment]
@grover Thanks for the heads up.  I am working on a fixing those now.

**Comment by cmaurer** [comment]
@grover fixed the major ones.  The only ones left are low, and in devDependencies.
